### ISSUE TITLE
Allow users to create budgets

### ISSUE THREAD

**Issue by ianbro** [ianbro/BudgetTracker#3]
As a Budget Planner, I need to be able to create a new budget so that I can start planning my finances on this system.

Details:

When creating the top-most budget (it has no parent budget), it MUST use the SetAmount method of budgeting. This is because PercentAmount wouldn't make sense (Percent amount of what?) and Dynamic amount wouldn't be good either for various reasons. These reasons are that this would prevent any sub-budget from using PercentAmount since PercentAmount requires the parent budget to use SetAmount. Also, no one sets up a budget that isn't based off of a solid number. I don't budget for a dynamic monthly income based on how much I WANT to spend. I budget for a known monthly income.

The budget will have the following fields

- ID: unique numeric identifier for program to identify this budget.
- Name: string identifier so User can identify this budget.
- SetAmount: Static dollar amount available in this budget. (Used as alternate to PercentAmount)
- PercentAmount: Percent of Parent budget that this budget will have available. (Used as alternate to SetAmount)
- Duration: An object that contains the duration details for this budget. (See below)
- SubBudgets: All Budgets that are children to this budget. These budgets should not have CalculatedAmounts that add up to greater than this budgets Calculated amount. That wouldn't make sense since they use money from this budget.

And the following calculated properties (calculations, not stored properties)
- CalculatedAmount: 1 of 3 things:
    - If SetAmount is not null, this takes on that value
    - Else If PercentAmount is not null, this takes on that percent of it's parents budget. This can only be used if it's parent budget's SetAmount is not null. Otherwise, this is useless because it doesn't have an amount to be a percentage of.
    - Else this takes on the total sum of the Calculated budgets (not including ones using percents) of each of it's child sub-budgets

The Duration class will contain the following fields:

- ID: primary key
- DurationQuantity: Used if this duration is for every x number of ____s (ex. every 30 days). This is the quantity of that duration.
- DurationUnit: Used if this duration is for every x number of ____s (ex. every 30 days). This is the unit of measurement of that duration such as "DAYS" or "YEARS".
- Begin Date: Used if this duration starts and ends on specified dates. This is the date that that this budget starts. This is only the day of the month.
- Begin Month: Used if this duration starts and ends on specified dates. This is the month that that this budget starts. This is only the month number.
- Stop Date: Used if this duration starts and ends on specified dates. This is the date that that this budget stops. This is only the day of the month.
- Number of Months: Used if this duration starts and ends on specified dates. This is the number of months before the budget stops. The specific date in the computed end date (this many months after Begin Month) is specified in Stop Date.

**Comment by BenjaminGroseclose** [comment]
@ianbro Looking at this how will we be able to determine the parent budget, we would need to have some sort of reference to it in here. 
Also how we know when to reset the duration?
