### ISSUE TITLE
Fetch budget tree API endpoint

### ISSUE THREAD

**Issue by ianbro** [ianbro/BudgetTracker#63]
Story: #9 

Create API endpoint that returns a master budget by ID and the full tree of its' sub budgets with details.

**Comment by BenjaminGroseclose** [comment]
@ianbro So is this returning the full list of their budgets, every one of them or will with full details or just some like it the name and set amount?

**Comment by ianbro** [comment]
It should return a single root budget with it's entire tree of sub-budgets. All budgets in the response should have all their direct details/relationships loaded (except owner since that's already in the context of the request so there's no need to go fetch it again).
