### ISSUE TITLE
Prevent Users from entering a duration for sub budgets

### ISSUE THREAD

**Issue by BenjaminGroseclose** [ianbro/BudgetTracker#71]
#61 #60 

Users should not be able to enter budget duration if the budget is a sub budget.

**Comment by ianbro** [comment]
See what I said on #61. We don't need to prevent it... we would just not add a form on the UI creation. This really should just be on the issue that we create when creating the UI. The form should never be added in the first place.

**Comment by ianbro** [comment]
See comments on #61. Closing this.
